(()=>{
'use strict';
const A=440.81167345,B=2161.51845819,P='tipaq-experiment-v2-';
const $=id=>document.getElementById(id);
const cash=n=>Number.isFinite(n)?new Intl.NumberFormat('fr-CA',{style:'currency',currency:'CAD',maximumFractionDigits:0}).format(n):'—';
const dateQC=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Toronto',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function rows(){const out=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.startsWith(P)){try{const r=JSON.parse(localStorage.getItem(k));if(r?.date)out.push(r)}catch(e){}}}return out.sort((a,b)=>a.date.localeCompare(b.date))}
const valid=r=>[r.sp,r.tsx,r.actual].every(Number.isFinite);
function fit(data){if(data.length<8)return null;const avg=a=>a.reduce((s,v)=>s+v,0)/a.length;const sp=data.map(r=>r.sp),ts=data.map(r=>r.tsx),ys=data.map(r=>r.actual),ms=avg(sp),mt=avg(ts),my=avg(ys);const sd=a=>Math.sqrt(avg(a.map(v=>(v-avg(a))**2)));const ss=sd(sp),st=sd(ts);if(ss<1e-8||st<1e-8)return null;const X=sp.map(v=>(v-ms)/ss),T=ts.map(v=>(v-mt)/st),Y=ys.map(v=>v-my),n=data.length,lambda=.15*n;const xx=X.reduce((s,v)=>s+v*v,lambda),tt=T.reduce((s,v)=>s+v*v,lambda),xt=X.reduce((s,v,i)=>s+v*T[i],0),xy=X.reduce((s,v,i)=>s+v*Y[i],0),ty=T.reduce((s,v,i)=>s+v*Y[i],0),det=xx*tt-xt*xt;if(det<1e-8)return null;const a=(xy*tt-ty*xt)/det/ss,b=(ty*xx-xy*xt)/det/st;return{a,b,c:my-a*ms-b*mt}}
function syncActuals(){if(typeof weeklyArchive==='undefined')return;const map={};Object.entries(weeklyArchive).forEach(([key,w])=>(w.days||[]).forEach((d,i)=>{const dt=new Date(key+'T12:00:00');dt.setDate(dt.getDate()+i);if(Number.isFinite(d[2]))map[dt.toISOString().slice(0,10)]=d[2]}));rows().forEach(r=>{if(Number.isFinite(map[r.date])&&r.actual!==map[r.date]){r.actual=map[r.date];localStorage.setItem(P+r.date,JSON.stringify(r))}})}
function saveClose(d){if(!d||![d.sp,d.tsx].every(Number.isFinite))return;const date=d.date||dateQC(),key=P+date;if(localStorage.getItem(key))return;const training=rows().filter(r=>r.date<date&&valid(r)),model=fit(training);localStorage.setItem(key,JSON.stringify({date,sp:d.sp,tsx:d.tsx,baseline:A*d.sp+B*d.tsx,experimental:model?model.c+model.a*d.sp+model.b*d.tsx:null,actual:null,trainingCount:training.length}));render()}
const main=$('app');if(!main)return;
const nav=document.createElement('div');nav.className='card';nav.innerHTML='<button type="button" id="openExperimental">Modèle expérimental →</button>';main.insertBefore(nav,main.children[2]);
const panel=document.createElement('section');panel.id='experimentalPage';panel.className='hidden';panel.innerHTML='<button type="button" id="backDashboard">← Retour</button><div class="card"><h2>Modèle expérimental — optimisation</h2><p class="muted">Régression ridge, entraînée sur au moins 8 séances complètes. Prévisions figées avant connaissance du rendement réel. Le modèle principal reste inchangé.</p><p id="optStatus"></p><p class="formula" id="optCoefficients"></p><p id="optMetrics"></p></div><div class="card"><h2>Évolution de la précision</h2><p class="muted">Erreur absolue moyenne cumulative (en $) : plus bas signifie plus précis.</p><p><span style="color:#5ea7ff">●</span> Actuel &nbsp; <span style="color:#52d9a0">●</span> Expérimental</p><canvas id="optAccuracyChart" style="width:100%;height:240px"></canvas><p id="optChartSummary"></p></div><div class="card"><h2>Comparaison des séances</h2><div style="overflow-x:auto"><table><thead><tr><th>Date</th><th>Actuel</th><th>Expérimental</th><th>Réel</th></tr></thead><tbody id="optRows"></tbody></table></div><p class="muted"><small>Données enregistrées localement sur cet appareil. Ne pas effacer les données du site. Les données historiques manquantes ne sont pas inventées.</small></p></div>';main.appendChild(panel);
const original=[...main.children].filter(e=>e!==panel);
function show(experimental){original.forEach(e=>e.classList.toggle('hidden',experimental));panel.classList.toggle('hidden',!experimental);if(experimental)render();else if(typeof drawChart==='function')requestAnimationFrame(drawChart);window.scrollTo(0,0)}
$('openExperimental').onclick=()=>show(true);$('backDashboard').onclick=()=>show(false);
function chart(data){const canvas=$('optAccuracyChart'),ctx=canvas.getContext('2d'),w=Math.max(290,canvas.getBoundingClientRect().width),h=240,dpr=devicePixelRatio||1;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);let sumA=0,sumB=0;const points=data.map((r,i)=>{sumA+=Math.abs(r.baseline-r.actual);sumB+=Math.abs(r.experimental-r.actual);return{a:sumA/(i+1),b:sumB/(i+1)}});if(!points.length){ctx.fillStyle='#9da9b5';ctx.font='12px system-ui';ctx.fillText('En attente des comparaisons prospectives.',10,110);$('optChartSummary').textContent='Aucune séance comparable pour le moment.';return}const max=Math.max(1,...points.flatMap(p=>[p.a,p.b]))*1.15,L=55,R=15,T=15,BT=35,x=i=>L+(w-L-R)*(points.length===1?.5:i/(points.length-1)),y=v=>h-BT-v/max*(h-T-BT);ctx.strokeStyle='#556170';ctx.beginPath();ctx.moveTo(L,T);ctx.lineTo(L,h-BT);ctx.lineTo(w-R,h-BT);ctx.stroke();ctx.fillStyle='#9da9b5';ctx.font='12px system-ui';ctx.fillText(Math.round(max)+' $',3,T+6);ctx.fillText('0 $',15,h-BT);[['a','#5ea7ff'],['b','#52d9a0']].forEach(([k,color])=>{ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=2;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(x(i),y(p[k])):ctx.moveTo(x(i),y(p[k])));ctx.stroke();points.forEach((p,i)=>{ctx.beginPath();ctx.arc(x(i),y(p[k]),3,0,Math.PI*2);ctx.fill()})});$('optChartSummary').textContent='Erreur moyenne : actuel '+cash(points.at(-1).a)+' ; expérimental '+cash(points.at(-1).b)+' ('+points.length+' séances).'}
function render(){syncActuals();const data=rows(),training=data.filter(valid),model=fit(training),ready=data.filter(r=>Number.isFinite(r.actual)&&Number.isFinite(r.experimental)&&Number.isFinite(r.baseline));$('optStatus').textContent=model?'Modèle entraîné sur '+training.length+' séances complètes.':'Apprentissage : '+training.length+'/8 séances complètes disponibles.';$('optCoefficients').textContent=model?'Estimation = '+model.c.toFixed(2)+' + '+model.a.toFixed(2)+' × Δ S&P (%) + '+model.b.toFixed(2)+' × Δ TSX (%)':'Coefficients expérimentaux en attente de données.';$('optMetrics').textContent=ready.length?'Comparaison prospective disponible sur '+ready.length+' séances.':'Comparaison prospective en attente de données.';$('optRows').innerHTML=data.slice().reverse().map(r=>'<tr><td>'+r.date+'</td><td>'+cash(r.baseline)+'</td><td>'+cash(r.experimental)+'</td><td>'+cash(r.actual)+'</td></tr>').join('')||'<tr><td colspan="4">Aucune séance expérimentale enregistrée.</td></tr>';chart(ready)}
window.addEventListener('tipaq-final-market-close',e=>saveClose(e.detail));window.addEventListener('resize',()=>{if(!panel.classList.contains('hidden'))render()});render();
})();